//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-548 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.12 at 04:51:45 PM CST 
//


package com.edi.test.restful;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BmscEventType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BmscEventType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="Version" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="NotificationType" use="required" type="{http://www.embmsbmscnbi.com}NotificationsType" />
 *       &lt;attribute name="EMBMSSessionId" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
 *       &lt;attribute name="DeliverySessionId" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
 *       &lt;attribute name="DeliveryInstanceId" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
 *       &lt;attribute name="Description" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="FileURI" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;attribute name="ContentId" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BmscEventType")
public class BmscEventType {

    @XmlAttribute(name = "Version", required = true)
    protected String version;
    @XmlAttribute(name = "NotificationType", required = true)
    protected String notificationType;
    @XmlAttribute(name = "EMBMSSessionId")
    @XmlSchemaType(name = "unsignedInt")
    protected Long embmsSessionId;
    @XmlAttribute(name = "DeliverySessionId")
    @XmlSchemaType(name = "unsignedInt")
    protected Long deliverySessionId;
    @XmlAttribute(name = "DeliveryInstanceId")
    @XmlSchemaType(name = "unsignedInt")
    protected Long deliveryInstanceId;
    @XmlAttribute(name = "Description")
    protected String description;
    @XmlAttribute(name = "FileURI")
    @XmlSchemaType(name = "anyURI")
    protected String fileURI;
    @XmlAttribute(name = "ContentId")
    @XmlSchemaType(name = "unsignedInt")
    protected Long contentId;

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the notificationType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNotificationType() {
        return notificationType;
    }

    /**
     * Sets the value of the notificationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotificationType(String value) {
        this.notificationType = value;
    }

    /**
     * Gets the value of the embmsSessionId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getEMBMSSessionId() {
        return embmsSessionId;
    }

    /**
     * Sets the value of the embmsSessionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setEMBMSSessionId(Long value) {
        this.embmsSessionId = value;
    }

    /**
     * Gets the value of the deliverySessionId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getDeliverySessionId() {
        return deliverySessionId;
    }

    /**
     * Sets the value of the deliverySessionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setDeliverySessionId(Long value) {
        this.deliverySessionId = value;
    }

    /**
     * Gets the value of the deliveryInstanceId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getDeliveryInstanceId() {
        return deliveryInstanceId;
    }

    /**
     * Sets the value of the deliveryInstanceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setDeliveryInstanceId(Long value) {
        this.deliveryInstanceId = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the fileURI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileURI() {
        return fileURI;
    }

    /**
     * Sets the value of the fileURI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileURI(String value) {
        this.fileURI = value;
    }

    /**
     * Gets the value of the contentId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getContentId() {
        return contentId;
    }

    /**
     * Sets the value of the contentId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setContentId(Long value) {
        this.contentId = value;
    }

}
